language: python
python:
  - "3.4"
# command to install dependencies
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
addons:
  firefox: "35.0"
install:
  - "pip install selenium"
  - "pip install pytest"
# command to run tests
script: py.test tests/index_tests.py